IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TILT_Tag_Note]') AND type in (N'U'))
ALTER TABLE [dbo].[TILT_Tag_Note] DROP CONSTRAINT IF EXISTS [FK_TILT_Tag_Note_TILT_Tag]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TILT_Tag_Note]') AND type in (N'U'))
ALTER TABLE [dbo].[TILT_Tag_Note] DROP CONSTRAINT IF EXISTS [FK_TILT_Tag_Note_TILT_Note]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TILT_Note]') AND type in (N'U'))
ALTER TABLE [dbo].[TILT_Note] DROP CONSTRAINT IF EXISTS [FK_TILT_Note_TILT_URL]
GO
DROP TABLE IF EXISTS [dbo].[TILT_URL]
GO
DROP TABLE IF EXISTS [dbo].[TILT_Tag_Note]
GO
DROP TABLE IF EXISTS [dbo].[TILT_Tag]
GO
DROP TABLE IF EXISTS [dbo].[TILT_Note]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TILT_Note](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[IDURL] [bigint] NOT NULL,
	[Text] [nvarchar](150) NOT NULL,
	[Link] [nvarchar](500) NULL,
	[ForDate] [datetime] NULL,
	[TimeZoneString] [nvarchar](350) NULL,
	
 CONSTRAINT [PK_TILT_Note] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TILT_Tag](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_TILT_Tag] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TILT_Tag_Note](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[IDTag] [bigint] NOT NULL,
	[IDNote] [bigint] NOT NULL,
 CONSTRAINT [PK_TILT_Tag_Note] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TILT_URL](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[URLPart] [nvarchar](10) NOT NULL,
	[Secret] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TILT_URL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TILT_Note]  WITH CHECK ADD  CONSTRAINT [FK_TILT_Note_TILT_URL] FOREIGN KEY([IDURL])
REFERENCES [dbo].[TILT_URL] ([ID])
GO
ALTER TABLE [dbo].[TILT_Note] CHECK CONSTRAINT [FK_TILT_Note_TILT_URL]
GO
ALTER TABLE [dbo].[TILT_Tag_Note]  WITH CHECK ADD  CONSTRAINT [FK_TILT_Tag_Note_TILT_Note] FOREIGN KEY([IDNote])
REFERENCES [dbo].[TILT_Note] ([ID])
GO
ALTER TABLE [dbo].[TILT_Tag_Note] CHECK CONSTRAINT [FK_TILT_Tag_Note_TILT_Note]
GO
ALTER TABLE [dbo].[TILT_Tag_Note]  WITH CHECK ADD  CONSTRAINT [FK_TILT_Tag_Note_TILT_Tag] FOREIGN KEY([IDTag])
REFERENCES [dbo].[TILT_Tag] ([ID])
GO
ALTER TABLE [dbo].[TILT_Tag_Note] CHECK CONSTRAINT [FK_TILT_Tag_Note_TILT_Tag]
GO
