name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run:  |
            cd src/backend/Net6/NetTilt 
            dotnet restore
    - name: Build
      run:  |
            cd src/backend/Net6/NetTilt 
            dotnet build --no-restore

    - name: Test
      run: |
            cd src/backend/Net6/NetTilt 
            cd NetTilt.Tests
            dotnet test --no-build #--verbosity normal
    
    - name: premark
      shell: pwsh
      run: |
         cd src/backend/Net6/NetTilt/NetTilt.Tests
         dir bin/Debug/net6.0/Reports/*.md
         $test=Get-Content bin/Debug/net6.0/Reports/LightBDDReport.md
         echo "action_state=yellow" >> $GITHUB_ENV
         echo "test_mkd=$test" >> $GITHUB_ENV

    - name: mark
      run: |
         echo ‘### Hello world! :rocket:’ >> $GITHUB_STEP_SUMMARY
         echo "${{ env.action_state }}" >> $GITHUB_STEP_SUMMARY
         echo "${{ env.test_mkd }}" >> $GITHUB_STEP_SUMMARY         
         echo ‘### Hello world! :rocket:’ >> $GITHUB_STEP_SUMMARY