name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    #runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai
    # - uses: szenius/set-timezone@v1.0
      # with:
        # timezoneLinux: "Europe/Bucharest"
        # timezoneMacos: "Europe/Bucharest"
        # timezoneWindows: "Europe/Bucharest"
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run:  |
            cd src/backend/Net6/NetTilt 
            dotnet restore
    - name: Build
      run:  |
            cd src/backend/Net6/NetTilt 
            dotnet build --no-restore

    - name: Test 
      run: |
            cd src/backend/Net6/NetTilt 
            cd NetTilt.Tests
            dotnet test --no-build #--verbosity normal
    
    - name: tests for zyborg
      uses: zyborg/dotnet-tests-report@v1
      with:
        skip_check_run: true
        project_path: src/backend/Net6/NetTilt/NetTilt.Tests/
        report_name: tilt_tests
        report_title: TILT Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
        gist_name: tilt_tests.md
        gist_badge_message: '__'
        gist_badge_label: 'TILT TESTS: %Counters_passed%/%Counters_total%'
        gist_token: ${{ secrets.GIST_TOKEN }}
        trx_xsl_path: trx2md.xsl

    - name: test
      shell: pwsh
      run:  |
            cd src/backend/Net6/NetTilt 
            Get-ChildItem -Filter trx2md.xsl -Recurse
            

    - name: premark
      shell: pwsh
      run: |
         cd src/backend/Net6/NetTilt/NetTilt.Tests
         dir bin/Debug/net6.0/Reports/*.md
         $test=(Get-Content bin/Debug/net6.0/Reports/LightBDDReport.md)  
         # $test=(Get-Content bin/Debug/net6.0/Reports/LightBDDReport.md)  -join ' <br /> '
         #  $test=(Get-Content bin/Debug/net6.0/Reports/LightBDDReport.md)  -join '\'
         #  $test=(Get-Content bin/Debug/net6.0/Reports/LightBDDReport.md)  -join '&nbsp;'
         $test = $test -replace '"',''''
         #$test = $test -replace '<br /> #','#'         
         echo "action_state=yellow"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
         echo "test_mkd=$test"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

    - name: mark
      run: |
         echo "${{ env.action_state }}" >> $GITHUB_STEP_SUMMARY
         cat  src/backend/Net6/NetTilt/NetTilt.Tests/bin/Debug/net6.0/Reports/LightBDDReport.md  >> $GITHUB_STEP_SUMMARY      
