name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'
          

      - name: Build with dotnet
        run: |
            cd src/backend/Net6/NetTilt 
            dotnet build --configuration Release

      - name: Build Angular Site 1
        shell: pwsh
        run: |
            node -v
            npm -v
            cd src/frontend/AngTilt14/
            npm i
            npm run buildAzure
            remove-item ..\..\backend\Net6\NetTilt\NetTilt\NetTilt.WebAPI\wwwroot\AngTilt\index.html
            Copy-Item .\dist\AngTilt\* ..\..\backend\Net6\NetTilt\NetTilt\NetTilt.WebAPI\wwwroot\AngTilt\
      - name: dotnet publish
        shell: pwsh
        run: |
            cd src/backend/Net6/NetTilt
            dotnet tool restore
            gci
            dotnet dotnet-project-licenses -i ./NetTilt/NetTilt.WebAPI -o --outfile NetTilt\NetTilt.WebAPI\wwwroot\netcorelicences.txt -t
            # ls -lh
            .\AOPMethod.ps1
            cd NetTilt/NetTilt.WebAPI 
            copy-item ./wwwroot/AngTilt/3rdpartylicenses.txt ./wwwroot/ 
            gci wwwroot
            dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp -r linux-x64

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TILTWebApp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0865EB8DA0C847FF9878C2EF8E6AA38C }}
          package: .